name: Release drafter

on:
  workflow_call:

jobs:
  update_release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Detect version updated
        id: version-updated
        uses: MontyD/package-json-updated-action@1.0.1
      - name: Draft a new release
        if: steps.version-updated.outputs.has-updated
        uses: release-drafter/release-drafter@v5
        with:
          config-name: changelog-generator.yml
          tag: v${{ steps.version-updated.outputs.current-package-version }}
          publish: true
      - name: Update a draft release
        uses: release-drafter/release-drafter@v5
        if: ${{ !steps.version-updated.outputs.has-updated }}
        with:
          config-name: changelog-generator.yml
